---
title: "Baseline Reference Scenario - SB County NWL GHG emissions and storage"
author: "Carbon Counters"
date: "7/28/2020"
output: 
  html_document: 
    css: bootstrap.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = FALSE)
```

```{r}

# Attach packages
library(tidyverse)
library(tidyr)
library(here)
library(janitor)
library(plotly)
library(kableExtra)
library(effsize)
library(stargazer)
library(broom)
library(plotly)

```


```{r}
# Read in data files and clean up, created in carbon inventory script. These files contain # of acres of each ag class according to calag (no landfire). 

ag_12 <- read_csv(here::here("results", "ag_final_12.csv")) %>% 
  select(! c(pixels, sqmeter))
ag_16 <- read_csv(here::here("results", "ag_final_16.csv")) %>% 
  clean_names()
ag_16 <- ag_16[, c(1, 6, 2:5, 7)]
ag_19 <- read_csv(here::here("results", "ag_final_19.csv")) %>% 
  select(! c(pixels, sqmeter))

colnames <- c("class", "acres","abvgc", "soilc", "noemit", "net", "year")
colnames(ag_12) = colnames
colnames(ag_16) = colnames
colnames(ag_19) = colnames

#Add in rangeland values from cal ag

# First, use carbon inventory to get average carbon values per acre
inventory <- read_csv(here("results", "inventory_16.csv")) %>% 
  clean_names

shrub_grass <- inventory %>% 
  filter(landcover_classification %in% c("Grassland","Shrubland")) %>% 
  mutate(soil_avg = total_soil_carbon_mtco2e/acres) %>% 
  mutate(abvg_avg = total_aboveground_carbon_mt_co2e/acres)
  
avg_soil_rangel <- weighted.mean(shrub_grass$soil_avg, shrub_grass$acres)
avg_abvg_rangel <- weighted.mean(shrub_grass$abvg_avg, shrub_grass$acres)

# crop report #s https://countyofsb.org/agcomm/cropReportArchive.sbc

range_acre_19 <- 573678
range_acre_12 <- 584125
range_acre_16 <- 586047

range_data <- data.frame(class = "Rangeland", "acres" = c(range_acre_12, range_acre_16, range_acre_19), "abvgc" = 0, "soilc" = 0, "noemit" = 0, "net" = 0, "year" = c(2012, 2016, 2019)) %>% 
  mutate(abvgc = avg_abvg_rangel*acres) %>% 
  mutate(soilc = avg_soil_rangel*acres) %>% 
  mutate(net = abvgc+soilc)

# make big dataframe to make calculations easier

all_ag_df <- rbind(ag_12, ag_16) %>% 
  rbind(ag_19) %>% 
  rbind(range_data) %>% 
  filter(class != "Total") 

all_ag_df_wide <- all_ag_df %>% 
  pivot_wider(names_from = class,
              values_from = c(acres, abvgc, soilc, noemit, net)) %>% 
  clean_names()

```


```{r}

## First, we'll make a data frame of years out to 2030
 
predict_df_30_acres <- data.frame(year = c(2012, 2016, 2019, 2030))

# Next we will build models to fit a linear regression to each crop category along with total ag acreage

select_ag <- all_ag_df_wide %>% 
  select(2:36)

ag_names <- colnames(select_ag)

res_list_plots <- vector("list", length = length(ag_names)) %>% 
  setNames(ag_names)

# first, linear regressions

fx_lm <- function(name) {

  lm_loop <- lm(all_ag_df_wide[[name]] ~ year, data = all_ag_df_wide)
  
}

all_lms <- lapply(ag_names, fx_lm) %>% 
  setNames(ag_names)

all_lms[[1]] # cool

# Now we will use these models to predict acreage (total and per crop type) in 2030

fx_predict <- function(lm) {
  
  predict_run_loop <- predict(lm, newdata = predict_df_30_acres)
  predict_df_loop <- data.frame(predict_df_30_acres, predict_run_loop)
  predict_df_loop <- predict_df_loop
  
}

looped_predict_dfs <- lapply(all_lms, fx_predict) %>% 
  setNames(ag_names)

looped_predict_dfs[[1]] # great

# These plots compare real data to the regression

for (name in ag_names) {
  plot <- print(ggplot() + 
  geom_point(data = all_ag_df_wide, aes(x = year, y = all_ag_df_wide[[name]])) +
  geom_line(data = looped_predict_dfs[[name]], aes(x = year, y = predict_run_loop)) +
  theme_minimal() + 
  labs(x = "year",
       y = paste(name)))
  
}

res_list_plots[[name]] <- plot

res_list_plots

```

```{r}

#create big dataframe of all predicted values (same units), easier for doing visualizations

#first, change column names
for(name in ag_names){
  
  colnames(looped_predict_dfs[[name]]) <- c("year", name)
  
}

# merge dataframes, common column = year
all_predict_df<- looped_predict_dfs %>% 
  reduce(full_join, by = "year")

# make this dataframe tidy
tidy_predict_df <- all_predict_df %>% 
  pivot_longer(!year,
               names_to = c("variable", "land_class"),
               names_sep = "_",
               values_to = "value")

# add totals
totals_predict <- tidy_predict_df %>% 
  group_by(variable, year) %>% 
  summarise(value = sum(value)) %>% 
  mutate(land_class = "total_allclasses") %>% 
  relocate(year, variable, land_class, value)

# put it together
final_predict_df <- bind_rows(tidy_predict_df, totals_predict)

# save as csv
write_csv(final_predict_df, here("results", "all_predictions.csv"))

# do the same for observed values

tidy_observed <- all_ag_df %>% 
  pivot_longer(cols = 2:6,
               names_to = "variable",
               values_to = "value") %>% 
  rename(land_class = class) %>% 
  relocate(year, variable, land_class, value)

totals_observed <- tidy_observed %>% 
  group_by(variable, year) %>% 
  summarise(value = sum(value)) %>% 
  mutate(land_class = "total_allclasses") %>% 
  relocate(year, variable, land_class, value)

final_observed_df <- bind_rows(tidy_observed, totals_observed)

write_csv(final_predict_df, here("results", "all_ag_observations.csv"))


```

Plotting results

```{r}

# Making some plots

# facet wrap easy plot

# ggplot(data = tidy_predict_df, aes(x = year, y = value, group = land_class))+
  # geom_line(aes(color = land_class))+
  # theme_minimal()+
  # facet_wrap(~variable, scales = "free_y")

# acres_graph <- ggplot(data =  subset(tidy_predict_df, variable == "acres"), aes(x = year, y = value, group = land_class))+
  # geom_line(aes(color = land_class))+
  # theme_minimal()+
  # stat_summary(fun.y = sum, na.rm = TRUE, group = 3, color = 'black', geom ='line', label = "total")

# ggplotly(acres_graph)


```

