---
title: "data_visualizations"
author: "Alicia Fennell"
date: "1/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen=999)

# Attach packages
library(tidyverse)
library(tidyr)
library(here)
library(janitor)
library(plotly)
library(kableExtra)
library(effsize)
library(stargazer)
library(broom)
library(plotly)
library(gg.gap)
library(tidyverse)
library(viridis)
library(hrbrthemes)
library(mapdata)
library(ggmap)
library(sf)
library(tmap)
library(RColorBrewer)
library(maptools)
library(raster)
library(unikn)
library(treemapify)
library(scales)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(forcats)
library(scales)
library(waffle)
library(magrittr)
library(hrbrthemes)
library(lubridate)
```

```{r}
# ## GK 
## mapping?
ag_observations <- read_csv(here("results", "all_ag_observations.csv"))
ag_predictions <- read_csv(here("results", "all_predictions.csv")) 
point_coords <- read_csv(here("files", "mapping", "point_coords.csv"))

values <- read_csv(here("results", "all_points_values.csv")) %>% 
  replace(is.na(.), 0) %>% 
  mutate(net = (stock_soilc_mtco2e_pix + stock_abvgc_mtco2e_pixel - emit_no_mtco2e_pix))

all_coord_vals <- merge(point_coords, values, by = "pointid") %>% 
  dplyr::select(!c(2,3)) %>% 
  mutate(total_stock = stock_soilc_mtco2e_pix + stock_abvgc_mtco2e_pixel)

landcover_data <- all_coord_vals %>% 
  dplyr::select(lat, lon, reclass_cat)

# %>% 
#   st_as_sf(coords = c("lon","lat"))

#st_crs(landcover_data) = 102245

# 102245

#landcover_raster <- rasterize(landcover_data)

# county_outline <- read_sf(here("files", "mapping", "sb_county.shp"))

# heat map of net carbon storage
ggplot(all_coord_vals, aes(x=lon, y=lat, z = total_stock, color = total_stock)) + 
  stat_summary_hex() +
  theme_void() +
  scale_fill_distiller(palette = "YlGn", trans = "reverse") +
  labs(fill = "")

ggsave(here("files", "figs", "heatmap_net.png"))
  
#scale_color_manual(brewer.pal="YlOrRd", direction=-1)

# colourCount = length(unique(landcover_data$reclass_cat))
# getPalette = colorRampPalette(brewer.pal(12, "Set3"))
# 
# # attempt landcover map
# 
# ggplot(data = landcover_data) +
#   geom_sf(aes(fill = reclass_cat)) +
#   theme_void() +
#   scale_fill_manual(values = getPalette(colourCount))
# 
# ggplot()+
#   geom_sf(data = sf_map, size = 0.1, color = "darkgray")+
#   geom_sf(data = all_trees_spatial, aes (color = spp_common), size = .1)+
#   theme_void()


#   geom_sf(data = blackwood_acacia_sp, 
#           color = "red", 
#           size = 0.5) +
#   theme_void() +
#   labs(title = "Blackwood acacias in San Francisco")
# 
# ggplot() + 
#   geom_sf(data = all_coord_vals, aes(x = lon, y = lat, fill = reclass_cat)) +
#   scale_fill_brewer(palette = "Set3")
#   
  
    # ggplot2::annotate("text", x = -27, y = 72, label="Where people tweet about #Surf", colour = "black", size=5, alpha=1, hjust=0) +
    # ggplot2::annotate("segment", x = -27, xend = 10, y = 70, yend = 70, colour = "black", size=0.2, alpha=1) +
  #   theme_void() +
  #   #xlim(-30, 70) +
  #   #ylim(24, 72) +
  #   scale_fill_viridis(
  # option="B",
  # trans = "log",
  # breaks = c(1,7,54,403,3000),
  # name="net mt co2e",
  # guide = guide_legend( keyheight = unit(2.5, units = "mm"), keywidth=unit(10, units = "mm"), label.position = "bottom", title.position = 'top', nrow=1)
  #  )  +
  #   ggtitle( "" ) +
  #   theme(
  #     legend.position = c(0.8, 0.09),
  #     legend.title=element_text(color="black", size=8),
  #     text = element_text(color = "#22211d"),
  #     plot.background = element_rect(fill = "#f5f5f2", color = NA), 
  #     panel.background = element_rect(fill = "#f5f5f2", color = NA), 
  #     legend.background = element_rect(fill = "#f5f5f2", color = NA),
  #     plot.title = element_text(size= 13, hjust=0.1, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
  #   ) 

```

# ALICIA BELOW

```{r}

# Visualize impacts of carbon and nitrogen coefficients for management practices

# cp_coeff_df_raw <- read_csv(here("cometplanner", "coefficients - hsp - Combined.csv"))
# 
# cp_coeff_df <- cp_coeff_df_raw %>% 
#   clean_names() %>% 
#   mutate(no = as.numeric(no)) %>% 
#   select(2,3,6,7) %>% 
#   pivot_longer(cols = c(3,4),
#                names_to = "variable",
#                values_to = "value") %>% 
#   mutate(practice = str_extract(practice, "\\(.*?\\)")) %>% 
#   group_by(crop, variable) %>% 
#   filter(!duplicated(practice)) %>% 
#   filter(crop != "Orchard")
#   
# plots <- ggplot(cp_coeff_df, aes(x = practice, y = value, fill = crop, group = crop)) +
#   geom_col(position="dodge", width = .3) +
#   theme_minimal() + 
#   # facet_wrap(~ crop, nrow = 1) +
#   theme(panel.spacing = unit(0, "lines")) +
#   theme(panel.grid = element_line(color = "gray90"))
# 
# plots
# 
# gg.gap(plot=plots,
#        segments=c(8.5,17.5),
#        ylim=c(-2,20))

  #coord_flip()

```

```{r}

library(scales)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(forcats)
library(scales)
library(waffle)
library(magrittr)
library(hrbrthemes)
library(lubridate)

af_colors <- c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "green4", "purple4")

## Acreage change over time
## read in wide data 
pred_wide <- read_csv(here("results", "predictions_wide.csv")) 

## trying to make a dataframe to have percent change over time of ag acreage 
bar_30 <- ag_predictions %>% 
  filter(year == 2030)

## get 2019 values
bar_everything_else <- ag_observations
  
bar_together <- rbind(bar_30, bar_everything_else) %>% 
  filter(land_class != "total_allclasses") %>% 
  mutate(year = as.character(year)) %>% 
  mutate(land_class = str_to_title(land_class)) %>% 
  dplyr::filter(variable != "net") %>% 
  mutate(variable = factor(variable, levels = c("acres", "abvgc", "soilc", "noemit"))) %>% 
   mutate(land_class = ifelse(land_class == "Row", "Row Crop", land_class))

# pct_change <- acres_19_30 %>% 
  # group_by(land_class) %>% 
  # mutate(pct_change = (value - lag(value))/lag(value)*100) %>% 
  # replace(is.na(.), 0)
  
## make the graph - probably don't use
# ggplot() +
  geom_line(data = pct_change, aes(x = year, y = pct_change, group = land_class, color = land_class), size = 1) +
  theme_light() +
  scale_color_brewer(palette = "Set3", direction = -1)
  
## set colors

# colors <- usecol("pal_unikn_light", n = 8)

## bar chart
ggplot(data = bar_together, aes(fill = reorder(land_class,value), y = value, x = year)) +
  geom_bar(stat = "identity", width = .8) +
  scale_fill_manual(values = af_colors) +
  theme_minimal() +
  scale_x_discrete(expand = c(0, 0), labels = c("2012", "2016", "2019", "2030")) +
  scale_y_continuous(expand = c(0, 0), labels = scales::comma) +
  labs(x = "",
       y = "",
       fill = "Land class") +
  facet_wrap(~variable, scales = "free_y",
             labeller = labeller(variable = 
    c("abvgc" = "Aboveground Carbon (MT CO2e)",
      "acres" = "Acres",
      "net" = "Net (MT CO2e)",
      "noemit" = "N2O emissions (MT CO2e)",
      "soilc" = "Soil Carbon (MT CO2e)")))

ggsave(here("files", "figs", "barplots.png"))
       
treemap_30 <- ggplot(data = subset(acres_19_30_bar, year== 2030), aes(area = value, fill = land_class, label = land_class)) +
  geom_treemap() +
  scale_fill_manual(values = colors) +
  labs(title = "2030 acreage by land class",
       fill = "Land class") +
       geom_treemap_text(colour = "black", place = "centre",
                    grow = TRUE)

ggsave(here("files", "figs", "treemap_30.png"))

treemap_19 <- ggplot(data = subset(acres_19_30_bar, year== 2019), aes(area = value, fill = land_class, label = land_class)) +
  geom_treemap() +
  scale_fill_manual(values = colors) +
  labs(title = "2019 acreage by land class",
       fill = "Land class") +
       geom_treemap_text(colour = "black", place = "centre",
                    grow = TRUE)
                    
ggsave(treemap_19, here("files", "figs", "treemap_19.png"))

treemap_30
treemap_19

```
#### LET'S MAKE SOME LINE GRAPHS

```{r}

plot_predict <- ag_predictions %>% 
  mutate(land_class = str_to_title(land_class)) %>% 
  mutate(land_class = ifelse(land_class == "Row", "Row Crop", land_class)) %>% 
  filter(variable != "net") %>% 
  mutate(variable = factor(variable, levels = c("acres", "abvgc", "soilc", "noemit"))) %>% 
  mutate(land_class = ifelse(land_class == "Total_allclasses", "Total (all classes)", land_class))

plot_observes <- ag_observations %>% 
  mutate(land_class = str_to_title(land_class)) %>% filter(variable != "net") %>% 
  mutate(variable = factor(variable, levels = c("acres", "abvgc", "soilc", "noemit"))) %>% 
  mutate(land_class = ifelse(land_class == "Total_allclasses", "Total (all classes)", land_class))

line_plots <- ggplot() +
  geom_line(data = subset(plot_predict, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(plot_observes, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class)) +
  facet_wrap(~variable, scales = "free_y",
             labeller = labeller(variable = 
    c("abvgc" = "Aboveground Carbon (MT CO2e)",
      "acres" = "Acres",
      "net" = "Net (MT CO2e)",
      "noemit" = "N2O emissions (MT CO2e)",
      "soilc" = "Soil Carbon (MT CO2e)"))) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "",
       x = "") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plots

ggsave(here("files", "figs", "lineplots.jpg"))

line_plots_rangetotal <- ggplot() +
  geom_line(data = subset(plot_predict, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(plot_observes, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class)) +
  facet_wrap(~variable, scales = "free_y",
             labeller = labeller(variable = 
    c("abvgc" = "Aboveground Carbon (MT CO2e)",
      "acres" = "Acres",
      "net" = "Net (MT CO2e)",
      "noemit" = "N2O emissions (MT CO2e)",
      "soilc" = "Soil Carbon (MT CO2e)"))) +
  theme_minimal() +
  scale_color_manual(values = c("Rangeland" = "darkolivegreen3", "Total (all classes)" = "cornflowerblue")) +
  labs(color = "Land Class",
       y = "",
       x = "") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plots_rangetotal

ggsave(here("files", "figs", "lineplotsrange.jpg"))


```



```{r}
## Pie chart attempts
#Read in ag observations and projections 

ag_observations <- read_csv(here("results", "all_ag_observations.csv"))
ag_predictions <- read_csv(here("results", "all_predictions.csv")) 

## pie chart for composition of land in 2030 and line graph showing percent change 
## Attempting pie chart, starting with bar chart 

ag_acres_30 <- ag_predictions %>% 
  filter(variable == "acres") %>% 
  filter(year == "2030") %>% 
  mutate(percent = value / 745176.317) %>% 
  filter(land_class != "total_allclasses") %>% 
  mutate(across(is.numeric, ~ round(., 4))) %>% 
  mutate(percent_dis = c("2.18%", "6.23%", "0.46%", "2.25%", "8.28%", "5.26%", "75.34%"))

pred_bar <- ggplot(data = ag_acres_30, 
                   aes(x="", 
                       y= percent, 
                      fill= land_class))+
geom_bar(width = 1, stat = "identity")

pred_bar

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

## bar chart to pie chart 
pred_pie <- pred_bar + coord_polar("y", start=45) +
  theme_minimal() +
  scale_fill_manual(values=c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "darkolivegreen3", "green4", "purple4")) +
  blank_theme +
  guides(fill = guide_legend(title = "Land Classification")) +
  geom_label_repel(aes(label = percent_dis), size=3, show.legend = F, nudge_x = 1)

pred_pie

```


```{r}
## waffle plotting 
## waffle for acreage percentages in 2030
acre_pct_30 <- c("Rangeland"=151,
                 "Row Crops"=17,
                 "Fodder"=12,
                 "Vineyard"=11,
                 "Orchard"=4,
                 "Fallow"=4,
                 "Greenhouse"=1)

waffle(acre_pct_30, rows=10, size=0.6,  
       colors=c("darkolivegreen3", "green4", "goldenrod", "purple4", "darkred", "lightsteelblue", "lightslategrey"),  
       title="2030 Working Lands by Land Classification",
       xlab= expression("1 square" %~~% "0.5% of working lands")) +
  theme(plot.title = element_text(hjust = 0.5))

## waffle for carbon storage percentages in 2030
carbon_pct_30 <- c("Rangeland"=166,
                 "Row Crops"=10,
                 "Fodder"=11,
                 "Vineyard"=7,
                 "Orchard"=4,
                 "Fallow"=2,
                 "Greenhouse"=0)

waffle(carbon_pct_30, rows=10, size=0.6,  
       colors=c("darkolivegreen3", "green4", "goldenrod", "purple4", "darkred", "lightsteelblue", "lightslategrey"),  
       title="2030 Net Carbon by Land Classification",
       xlab= expression("1 square" %~~% "0.5% of net carbon in working lands")) +
  theme(plot.title = element_text(hjust = 0.5))

## waffle for n2o emissions percentages in 2030
n2o_pct_30 <- c("Rangeland"=0,
                 "Row Crops"=133,
                 "Fodder"=28,
                 "Vineyard"=14,
                 "Orchard"=25,
                 "Fallow"=0,
                 "Greenhouse"=0)

waffle(n2o_pct_30, rows=10, size=0.6,  
       colors=c("darkolivegreen3", "green4", "goldenrod", "purple4", "darkred", "lightsteelblue", "lightslategrey"),  
       title="2030 N2O Emissions by Land Classification",
       xlab= expression("1 square" %~~% "0.5% of N2O emissions from working lands")) +
  theme(plot.title = element_text(hjust = 0.5))


# ggplot(data = ag_acres_30) +
#   geom_waffle(aes(fill = land_class, 
#            values = percent)) +
#   scale_fill_manual(
#     values=c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "darkolivegreen3", "green4", "purple4"),
#     labels = c("Fruit", "Sammich", "Pizza", "test", "testag", "woo", "last")
#   ) +
#   coord_equal() +
#   theme_ipsum_rc(grid="") +
#   theme_enhance_waffle()
# 
# 
# waffle(ag_acres_30, rows=7, size=0.5, 
#        colors=c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "darkolivegreen3", "green4", "purple4"), 
#        title="Average Household Savings Each Year", 
#        xlab="1 square == $392")
```


```{r}
## Acreage change over time
## read in wide data 
pred_wide <- read_csv(here("results", "predictions_wide.csv")) 

## trying to make a dataframe to have percent change over time of ag acreage 
acres_predict <- final_predict_df %>% 
  filter(year %in% c(2012, 2030)) %>% 
  filter(variable == "acres") %>% 
  group_by(land_class) %>% 
  mutate(year = year(year)) %>% 
  mutate(pct_change = (value - lag(value))/lag(value))

## just rangelands
# ggplot(data = pred_wide)+
#   geom_line(aes(x = year, y = acres_rangeland))+
#   geom_line(aes(x = year, y = net_rangeland))
#   theme_minimal()

## 
ggplot(data = tidy_predict_df, aes(x = year, y = value, group = variable))+
  geom_line(aes(color = variable))+
  theme_minimal()+
  facet_wrap(~land_class, scales = "free_y")

## 
ggplot(data = tidy_predict_df, aes(x = year, y = value, group = land_class))+ 
  geom_line(aes(color = land_class))+
  theme_minimal()+ 
  facet_wrap(~variable, scales = "free_y")

## only acres and net 
ggplot(data = subset(tidy_predict_df, variable %in% c("acres", "net")), aes(x = year, y = value, group = land_class))+
  geom_line(aes(color = land_class))+
  theme_minimal()+
  facet_wrap(~variable, scales = "free_y")
```


```{r}

inventory_16 <- read_csv(here("results", "inventory_16.csv")) %>% 
  clean_names()

inventory_stocks <- inventory %>% 
  mutate(total_stocks = total_soil_carbon_mtco2e + total_aboveground_carbon_mt_co2e) 


```


>>>>>>> 331fd9099db1e819a5e4e28777382f95edfe89a0
