---
title: "GAVI VIZ"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen=999)

# Attach packages
library(raster)
library(tidyverse)
library(tidyr)
library(here)
library(janitor)
library(plotly)
library(kableExtra)
library(effsize)
library(stargazer)
library(broom)
library(plotly)
library(gg.gap)
library(tidyverse)
library(viridis)
library(hrbrthemes)
library(mapdata)
library(ggmap)
library(sf)
library(tmap)
library(RColorBrewer)
library(maptools)
library(raster)
library(unikn)
library(treemapify)
library(scales)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(forcats)
library(scales)
library(waffle)
library(magrittr)
library(hrbrthemes)
library(lubridate)
library(scales)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(forcats)
library(scales)
library(waffle)
library(magrittr)
library(hrbrthemes)
library(lubridate)
library(rgdal)

library(extrafont)
library(ggforce)
library(rasterize)
```

```{r}

# Set up

pred_wide <- read_csv(here("results", "predictions_wide.csv")) 

ag_observations <- read_csv(here("results", "all_ag_observations.csv"))

ag_predictions <- read_csv(here("results", "all_predictions.csv")) 

point_coords <- read_csv(here("files", "mapping", "point_coords.csv"))

values <- read_csv(here("results", "all_points_values.csv")) %>% 
  replace(is.na(.), 0) %>% 
  mutate(net = (stock_soilc_mtco2e_pix + stock_abvgc_mtco2e_pixel - emit_no_mtco2e_pix))

all_coord_vals <- merge(point_coords, values, by = "pointid") %>% 
  dplyr::select(!c(2,3)) %>% 
  mutate(total_stock = stock_soilc_mtco2e_pix + stock_abvgc_mtco2e_pixel)

cp_coeff_df_raw <- read_csv(here("cometplanner", "coefficients - hsp - Combined.csv"))

af_colors <- c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "green4", "purple4")

```

```{r}
# mapping
# landcover_data <- all_coord_vals %>% 
#   dplyr::select(lat, lon, reclass_cat)
# 
# coordinates(landcover_data) <- ~lon+lat
# 
# res <- 30/30
# 
# rast <- raster::raster(ext = raster::extent(coordinates), res = res)
# 
# landcover_raster <- raster::rasterize(landcover_data, field = reclass_cat)

# heat map of net carbon storage
ggplot(all_coord_vals, aes(x=lon, y=lat, z = total_stock, color = total_stock)) + 
  stat_summary_hex() +
  theme_void() +
  scale_fill_distiller(palette = "YlGn", trans = "reverse") +
  labs(fill = "")

ggsave(here("files", "figs", "heatmap_net.png"))
```

```{r, original line plots}

#### LET'S MAKE SOME LINE GRAPHS

plot_predict <- ag_predictions %>% 
  mutate(land_class = str_to_title(land_class)) %>% 
  mutate(land_class = ifelse(land_class == "Row", "Row Crop", land_class)) %>% 
  filter(variable != "net") %>% 
  mutate(variable = factor(variable, levels = c("acres", "abvgc", "soilc", "noemit"))) %>% 
  mutate(land_class = ifelse(land_class == "Total_allclasses", "Total (all classes)", land_class))

plot_observes <- ag_observations %>% 
  mutate(land_class = str_to_title(land_class)) %>% filter(variable != "net") %>% 
  mutate(variable = factor(variable, levels = c("acres", "abvgc", "soilc", "noemit"))) %>% 
  mutate(land_class = ifelse(land_class == "Total_allclasses", "Total (all classes)", land_class))

line_plots <- ggplot() +
  geom_line(data = subset(plot_predict, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(plot_observes, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class)) +
  facet_wrap(~variable, scales = "free_y",
             labeller = labeller(variable = 
    c("abvgc" = "Aboveground Carbon (MT CO2e)",
      "acres" = "Acres",
      "net" = "Net (MT CO2e)",
      "noemit" = "N2O emissions (MT CO2e)",
      "soilc" = "Soil Carbon (MT CO2e)"))) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "",
       x = "") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plots

ggsave(here("files", "figs", "lineplots.jpg"))

line_plots_rangetotal <- ggplot() +
  geom_line(data = subset(plot_predict, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(plot_observes, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class)) +
  facet_wrap(~variable, scales = "free_y",
             labeller = labeller(variable = 
    c("abvgc" = "Aboveground Carbon (MT CO2e)",
      "acres" = "Acres",
      "net" = "Net (MT CO2e)",
      "noemit" = "N2O emissions (MT CO2e)",
      "soilc" = "Soil Carbon (MT CO2e)"))) +
  theme_minimal() +
  scale_color_manual(values = c("Rangeland" = "darkolivegreen3", "Total (all classes)" = "cornflowerblue")) +
  labs(color = "Land Class",
       y = "",
       x = "") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))+
  theme(text = element_text(family = "Roboto"))


line_plots_rangetotal

ggsave(here("files", "figs", "lineplotsrange.jpg"))


```

```{r, revised line plots}

inventory_16 <- read_csv(here("results", "inventory_16.csv")) %>% 
  clean_names()

inventory_stocks <- inventory_16 %>% 
  mutate(total_stocks = total_soil_carbon_mtco2e + total_aboveground_carbon_mt_co2e) 

tstock_plot_predict <- ag_predictions %>% 
  mutate(land_class = str_to_title(land_class)) %>% 
  mutate(land_class = ifelse(land_class == "Row", "Row Crop", land_class)) %>% 
  filter(variable != "net") %>% 
  mutate(variable = as.character(variable)) %>% 
  mutate(land_class = ifelse(land_class == "Total_allclasses", "Total (all classes)", land_class)) %>% 
  filter(variable %in% c("soilc", "abvgc")) %>% 
  group_by(year, land_class) %>% 
  summarize(value = sum(value)) %>% 
  mutate(variable = "total_stock") %>% 
  dplyr::select(c(1, 4, 2, 3))

plot_predict <- data.frame(plot_predict)
tstock_plot_predict <- data.frame(tstock_plot_predict)

rev_plot_predict <- rbind(plot_predict, tstock_plot_predict)

rev_plot_predict <- as.data.frame(rev_plot_predict)%>% 
  dplyr::mutate(variable = as.character(variable))

tstock_plot_observes <- ag_observations %>% 
  mutate(land_class = str_to_title(land_class)) %>% filter(variable != "net") %>% 
  mutate(variable = as.character(variable)) %>% 
  mutate(land_class = ifelse(land_class == "Total_allclasses", "Total (all classes)", land_class)) %>% 
  filter(variable %in% c("soilc", "abvgc")) %>% 
  group_by(year, land_class) %>% 
  summarize(value = sum(value)) %>% 
  mutate(variable = "total_stock") %>% 
  dplyr::select(c(1, 4, 2, 3))

plot_observes <- data.frame(plot_observes)
tstock_plot_observes <- data.frame(tstock_plot_observes)

rev_plot_observes <- rbind(plot_observes, tstock_plot_observes) %>% 
  mutate(year = as.numeric(year)) %>% 
  mutate(variable = as.character(variable)) %>% 
  mutate(value = as.numeric(value)) %>% 
  mutate(land_class = as.character(land_class))

tstock_plot_all <- rev_plot_predict %>% 
  filter(year == "2030") %>% 
  mutate(year = as.numeric(year)) %>% 
  mutate(variable = as.character(variable)) %>% 
  mutate(value = as.numeric(value)) %>% 
  mutate(land_class = as.character(land_class))

tstock_plot_all <- rbind(tstock_plot_all, rev_plot_observes)

tstock_plot_acres <- tstock_plot_all %>% 
  filter(variable == "acres")

tstock_plot_stock <- tstock_plot_all %>% 
  filter(variable == "total_stock")

tstock_plot_n2o <- tstock_plot_all %>% 
  filter(variable == "noemit")

write_csv(rev_plot_predict, here("results", "shiny_predict_30.csv"))
write_csv(tstock_plot_all, here("results", "shiny_observed_30.csv"))

# Make plots again
line_plot_acres_rangetotal <- ggplot() +
  geom_line(data = subset(tstock_plot_acres, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(tstock_plot_acres, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3) +
  theme_minimal() +
  scale_color_manual(values = c("Rangeland" = "darkolivegreen3", "Total (all classes)" = "cornflowerblue")) +
  labs(color = "Land Class",
       y = "Acres",
       x = "",
       title = "Estimated Past and Projected Future Acres by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plot_acres_rangetotal

line_plot_acres_ag <- ggplot() +
  geom_line(data = subset(tstock_plot_acres, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(tstock_plot_acres, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "Acres",
       x = "",
      title = "Estimated Past and Projected Future Acres by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plot_acres_ag

line_plot_stock_ag <- ggplot() +
  geom_line(data = subset(tstock_plot_stock, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(tstock_plot_stock, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "MTCO2e",
       x = "",
        title = "Estimated Past and Projected Future Carbon Stocks by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plot_stock_ag

line_plot_stock_rangetotal <- ggplot() +
  geom_line(data = subset(tstock_plot_stock, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = subset(tstock_plot_stock, land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3) +
  theme_minimal() +
  scale_color_manual(values = c("Rangeland" = "darkolivegreen3", "Total (all classes)" = "cornflowerblue")) +
  labs(color = "Land Class",
       y = "MTCO2e",
       x = "",
       title = "Estimated Past and Projected Future Carbon Stocks by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plot_stock_rangetotal

line_plot_n2o <- ggplot() +
  geom_line(data = tstock_plot_n2o, aes(x = year, y = value, group = land_class, color = land_class), size = 1.2) +
  geom_point(data = tstock_plot_n2o, aes(x = year, y = value, group = land_class, color = land_class), size = 3) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +
  labs(color = "Land Class",
       y = "MTCO2e",
       x = "",
       title = "Estimated Past and Projected Future Nitrous Oxide Emissions by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30"))

line_plot_n2o

line_plot_acres_rangetotal
ggsave(here("files", "figs", "line_plot_acres_rangetotal.jpg"))

line_plot_acres_ag
ggsave(here("files", "figs", "line_plot_acres_ag.jpg"))

line_plot_n2o
ggsave(here("files", "figs", "line_plot_n2o.jpg"))

line_plot_stock_ag
ggsave(here("files", "figs", "line_plot_stock_ag.jpg"))

line_plot_stock_rangetotal
ggsave(here("files", "figs", "line_plot_stock_rangetotal.jpg"))

```


```{r, bar plots and treemaps}

# Bar plots - not use not run

## trying to make a dataframe to have percent change over time of ag acreage 
# bar_30 <- ag_predictions %>% 
#   filter(year == 2030)
# 
# ## get 2019 values
# bar_everything_else <- ag_observations
#   
# bar_together <- rbind(bar_30, bar_everything_else) %>% 
#   filter(land_class != "total_allclasses") %>% 
#   mutate(year = as.character(year)) %>% 
#   mutate(land_class = str_to_title(land_class)) %>% 
#   dplyr::filter(variable != "net") %>% 
#   mutate(variable = factor(variable, levels = c("acres", "abvgc", "soilc", "noemit"))) %>% 
#    mutate(land_class = ifelse(land_class == "Row", "Row Crop", land_class))

# pct_change <- acres_19_30 %>% 
  # group_by(land_class) %>% 
  # mutate(pct_change = (value - lag(value))/lag(value)*100) %>% 
  # replace(is.na(.), 0)
  
## make the graph - probably don't use
# ggplot() +
  # geom_line(data = pct_change, aes(x = year, y = pct_change, group = land_class, color = land_class), size = 1) +
  # theme_light() +
  # scale_color_brewer(palette = "Set3", direction = -1)
  
## set colors

# colors <- usecol("pal_unikn_light", n = 8)

## bar chart
# ggplot(data = bar_together, aes(fill = reorder(land_class,value), y = value, x = year)) +
#   geom_bar(stat = "identity", width = .8) +
#   scale_fill_manual(values = af_colors) +
#   theme_minimal() +
#   scale_x_discrete(expand = c(0, 0), labels = c("2012", "2016", "2019", "2030")) +
#   scale_y_continuous(expand = c(0, 0), labels = scales::comma) +
#   labs(x = "",
#        y = "",
#        fill = "Land class") +
#   facet_wrap(~variable, scales = "free_y",
#              labeller = labeller(variable = 
#     c("abvgc" = "Aboveground Carbon (MT CO2e)",
#       "acres" = "Acres",
#       "net" = "Net (MT CO2e)",
#       "noemit" = "N2O emissions (MT CO2e)",
#       "soilc" = "Soil Carbon (MT CO2e)")))

# ggsave(here("files", "figs", "barplots.png"))
       
# treemap_30 <- ggplot(data = subset(acres_19_30_bar, year== 2030), aes(area = value, fill = land_class, label = land_class)) +
#   geom_treemap() +
#   scale_fill_manual(values = colors) +
#   labs(title = "2030 acreage by land class",
#        fill = "Land class") +
#        geom_treemap_text(colour = "black", place = "centre",
#                     grow = TRUE)
# 
# ggsave(here("files", "figs", "treemap_30.png"))
# 
# treemap_19 <- ggplot(data = subset(acres_19_30_bar, year== 2019), aes(area = value, fill = land_class, label = land_class)) +
#   geom_treemap() +
#   scale_fill_manual(values = colors) +
#   labs(title = "2019 acreage by land class",
#        fill = "Land class") +
#        geom_treemap_text(colour = "black", place = "centre",
#                     grow = TRUE)
#                     
# ggsave(treemap_19, here("files", "figs", "treemap_19.png"))
# 
# treemap_30
# treemap_19

```

```{r revised lineplots dotted}

labels <- unique(tstock_plot_acres$land_class)
  
rev_plot_predict <- rev_plot_predict %>% 
  mutate(year = as.numeric(year))

# Make plots again
updt_plot_acres_allclass <- ggplot() +
 geom_line(data = subset(rev_plot_predict, variable == "acres"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = tstock_plot_acres, aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +
  labs(color = "Land Class",
       y = "Acres",
       x = "",
       title = "Estimated Past and Projected Future Acres by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
  theme(plot.title = element_text(hjust = 0.5))

updt_plot_acres_allclass
ggsave(here("files", "figs", "dotted_acres_all.jpg"), height = 7, width = 10)

updt_plot_acres_ag <- ggplot() +
  geom_line(data = subset(rev_plot_predict, !land_class %in% c("Rangeland", "Total (all classes)") &  variable == "acres"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = subset(tstock_plot_acres, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "Acres",
       x = "",
      title = "Estimated Past and Projected Future Acres by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
  theme(plot.title = element_text(hjust = 0.5))
  
updt_plot_acres_ag
ggsave(here("files", "figs", "dotted_acres_ag.jpg"), height = 7, width = 10)

updt_plot_stock_ag <- ggplot() +
  geom_line(data = subset(rev_plot_predict, !land_class %in% c("Rangeland", "Total (all classes)") &  variable == "total_stock"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = subset(tstock_plot_stock, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "MT Carbon",
       x = "",
        title = "Estimated Past and Projected Future Carbon Stocks by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
  theme(plot.title = element_text(hjust = 0.5))

updt_plot_stock_ag
ggsave(here("files", "figs", "dotted_stock_ag.jpg"), height = 7, width = 10)

updt_plot_stock_all <- ggplot() +
  geom_line(data = subset(subset(rev_plot_predict, variable == "total_stock")), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = tstock_plot_stock, aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +  
  labs(color = "Land Class",
       y = "MT Carbon",
       x = "",
       title = "Estimated Past and Projected Future Carbon Stocks by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
  theme(plot.title = element_text(hjust = 0.5))

updt_plot_stock_all
ggsave(here("files", "figs", "dotted_stock_all.jpg"), height = 7, width = 10)

updt_plot_n2o <- ggplot() +
  geom_line(data = subset(rev_plot_predict, variable == "noemit"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = tstock_plot_n2o, aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +
  labs(color = "Land Class",
       y = "MTCO2e",
       x = "Year",
       title = "Nitrous Oxide Emissions by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
  theme(plot.title = element_text(hjust = 0.5, size = 28, margin=margin(0,0,40,0), family="Times", face="plain"),
        axis.text.x = element_text(size = 18, angle = 0, hjust = .5, vjust = .5, family="Times", face="plain"),
        axis.text.y = element_text(size = 18, angle = 0, hjust = 1, vjust = 0, family="Times", face="plain"),  
        axis.title.x = element_text(size = 22, angle = 0, hjust = .5, vjust = 0, margin=margin(15,0,0,0), family="Times", face="plain"),
        axis.title.y = element_text(size = 22, angle = 90, hjust = .5, vjust = .5, margin=margin(0,15,0,0), family="Times", face="plain"),
        legend.text = element_text(size = 22, margin=margin(0,0,10,0), family="Times", face="plain"),
        legend.title = element_text(size = 26, family="Times", face="plain"))

updt_plot_n2o
ggsave(here("alicia", "n2o.jpg"), height = 8, width = 13)
ggsave(here("files", "figs", "dotted_n2o.jpg"), height = 7, width = 10)
 
# library(showtext)
# font_add_google("Roboto", "Roboto")
# roboto <- "Roboto"
# myFont2
# font_files()
# font_families()

# margins top,right,bottom,left.

```

```{r}
## Alicia's edited figures / labels 


updt_plot_acres_allclass <- ggplot() +
 geom_line(data = subset(rev_plot_predict, variable == "acres"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = tstock_plot_acres, aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +
  labs(color = "Land Class",
       y = "Acres",
       x = "Year",
       title = "Acres by Land Class (All Working Lands)") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
 theme(plot.title = element_text(hjust = 0.5, size = 32, margin=margin(0,0,40,0), family="Times", face="plain"),
        axis.text.x = element_text(size = 24, angle = 0, hjust = .5, vjust = .5, family="Times", face="plain"),
        axis.text.y = element_text(size = 24, angle = 0, hjust = 1, vjust = 0, family="Times", face="plain"),  
        axis.title.x = element_text(size = 26, angle = 0, hjust = .5, vjust = 0, margin=margin(10,0,0,0), family="Times", face="plain"),
        axis.title.y = element_text(size = 26, angle = 90, hjust = .5, vjust = .5, margin=margin(0,15,0,0), family="Times", face="plain"),
        legend.text = element_text(size = 26, margin=margin(0,0,15,0), family="Times", face="plain"),
        legend.title = element_text(size = 28, family="Times", face="plain"))

updt_plot_acres_allclass
ggsave(here("alicia", "acres_all.jpg"), height = 8, width = 13)

updt_plot_acres_ag <- ggplot() +
  geom_line(data = subset(rev_plot_predict, !land_class %in% c("Rangeland", "Total (all classes)") &  variable == "acres"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = subset(tstock_plot_acres, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "Acres",
       x = "Year",
      title = "Acres by Land Class (Agriculture)") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
  theme(plot.title = element_text(hjust = 0.5, size = 32, margin=margin(0,0,40,0), family="Times", face="plain"),
        axis.text.x = element_text(size = 24, angle = 0, hjust = .5, vjust = .5, family="Times", face="plain"),
        axis.text.y = element_text(size = 24, angle = 0, hjust = 1, vjust = 0, family="Times", face="plain"),  
        axis.title.x = element_text(size = 26, angle = 0, hjust = .5, vjust = 0, margin=margin(10,0,0,0), family="Times", face="plain"),
        axis.title.y = element_text(size = 26, angle = 90, hjust = .5, vjust = .5, margin=margin(0,15,0,0), family="Times", face="plain"),
        legend.text = element_text(size = 26, margin=margin(0,0,15,0), family="Times", face="plain"),
        legend.title = element_text(size = 28, family="Times", face="plain"))
  
updt_plot_acres_ag
ggsave(here("alicia", "acres_ag.jpg"), height = 8, width = 13)

updt_plot_stock_ag <- ggplot() +
  geom_line(data = subset(rev_plot_predict, !land_class %in% c("Rangeland", "Total (all classes)") &  variable == "total_stock"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = subset(tstock_plot_stock, !land_class %in% c("Rangeland", "Total (all classes)")), aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = af_colors) +
  labs(color = "Land Class",
       y = "MT Carbon",
       x = "Year",
        title = "Carbon Stocks by Land Class (Agriculture)") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
   theme(plot.title = element_text(hjust = 0.5, size = 32, margin=margin(0,0,40,0), family="Times", face="plain"),
        axis.text.x = element_text(size = 24, angle = 0, hjust = .5, vjust = .5, family="Times", face="plain"),
        axis.text.y = element_text(size = 24, angle = 0, hjust = 1, vjust = 0, family="Times", face="plain"),  
        axis.title.x = element_text(size = 26, angle = 0, hjust = .5, vjust = 0, margin=margin(10,0,0,0), family="Times", face="plain"),
        axis.title.y = element_text(size = 26, angle = 90, hjust = .5, vjust = .5, margin=margin(0,15,0,0), family="Times", face="plain"),
        legend.text = element_text(size = 26, margin=margin(0,0,15,0), family="Times", face="plain"),
        legend.title = element_text(size = 28, family="Times", face="plain"))

updt_plot_stock_ag
ggsave(here("alicia", "carbon_ag.jpg"), height = 8, width = 13)

updt_plot_stock_all <- ggplot() +
  geom_line(data = subset(subset(rev_plot_predict, variable == "total_stock")), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = tstock_plot_stock, aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +  
  labs(color = "Land Class",
       y = "MT Carbon",
       x = "Year",
       title = "Carbon Stocks by Land Class (All Working Lands)") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
   theme(plot.title = element_text(hjust = 0.5, size = 32, margin=margin(0,0,40,0), family="Times", face="plain"),
        axis.text.x = element_text(size = 24, angle = 0, hjust = .5, vjust = .5, family="Times", face="plain"),
        axis.text.y = element_text(size = 24, angle = 0, hjust = 1, vjust = 0, family="Times", face="plain"),  
        axis.title.x = element_text(size = 26, angle = 0, hjust = .5, vjust = 0, margin=margin(10,0,0,0), family="Times", face="plain"),
        axis.title.y = element_text(size = 26, angle = 90, hjust = .5, vjust = .5, margin=margin(0,15,0,0), family="Times", face="plain"),
        legend.text = element_text(size = 26, margin=margin(0,0,15,0), family="Times", face="plain"),
        legend.title = element_text(size = 28, family="Times", face="plain"))

updt_plot_stock_all
ggsave(here("alicia", "carbon_all.jpg"), height = 8, width = 13)

updt_plot_n2o <- ggplot() +
  geom_line(data = subset(rev_plot_predict, variable == "noemit"), aes(x = year, y = value, group = land_class, color = land_class), size = .8, linetype = "dashed") +
  geom_point(data = tstock_plot_n2o, aes(x = year, y = value, group = land_class, color = land_class), size = 3.6) +
  theme_minimal() +
  scale_color_manual(values = c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "darkolivegreen3", "green4", "cornflowerblue", "purple4")) +
  labs(color = "Land Class",
       y = "MTCO2e",
       x = "Year",
       title = "Nitrous Oxide Emissions by Land Class") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks = c(2012, 2016, 2019, 2030), labels = c("'12", "'16", "'19", "'30")) +
  theme(plot.title = element_text(hjust = 0.5, size = 32, margin=margin(0,0,40,0), family="Times", face="plain"),
        axis.text.x = element_text(size = 24, angle = 0, hjust = .5, vjust = .5, family="Times", face="plain"),
        axis.text.y = element_text(size = 24, angle = 0, hjust = 1, vjust = 0, family="Times", face="plain"),  
        axis.title.x = element_text(size = 26, angle = 0, hjust = .5, vjust = 0, margin=margin(10,0,0,0), family="Times", face="plain"),
        axis.title.y = element_text(size = 26, angle = 90, hjust = .5, vjust = .5, margin=margin(0,15,0,0), family="Times", face="plain"),
        legend.text = element_text(size = 26, margin=margin(0,0,15,0), family="Times", face="plain"),
        legend.title = element_text(size = 28, family="Times", face="plain"))

updt_plot_n2o
ggsave(here("alicia", "n2o.jpg"), height = 8, width = 13)

```

