---
title: "Shiny Prep"
author: "GK AF MR"
date: "2/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(tidyverse)
library(tidyr)
library(here)
library(janitor)
library(plotly)
library(kableExtra)
library(effsize)
library(stargazer)
library(broom)
library(gg.gap)
library(tidyverse)
library(viridis)
library(hrbrthemes)
library(mapdata)
library(ggmap)
library(sf)
library(tmap)
library(RColorBrewer)
library(maptools)
library(unikn)
library(treemapify)
library(scales)
library(ggplot2)
library(waffle)
library(lubridate)
library(dplyr)
library(ggrepel)
library(forcats)
library(magrittr)
library(rgdal)
library(extrafont)
library(ggforce)
library(rasterize)
library(fasterize)
library(stars)

```

```{r, cache = TRUE}

# pred_wide <- read_csv(here("results", "predictions_wide.csv")) 

# ag_observations <- read_csv(here("results", "all_ag_observations.csv"))

# ag_predictions <- read_csv(here("results", "all_predictions.csv")) 

point_coords <- read_csv(here("files", "mapping", "point_coords.csv"))

values <- read_csv(here("results", "all_points_values.csv")) %>% 
  replace(is.na(.), 0) %>% 
  mutate(net = (stock_soilc_mtco2e_pix + stock_abvgc_mtco2e_pixel - emit_no_mtco2e_pix))

all_coord_vals <- merge(point_coords, values, by = "pointid") %>% 
  dplyr::select(!c(2,3)) %>% 
  mutate(total_stock = stock_soilc_mtco2e_pix + stock_abvgc_mtco2e_pixel)

# cp_coeff_df_raw <- read_csv(here("cometplanner", "coefficients - hsp - Combined.csv"))

# af_colors <- c("lightsteelblue", "goldenrod", "lightslategrey", "darkred", "sandybrown", "green4", "purple4")

```

```{r}
# county outline

counties <- read_sf(here("files", "mapping", "county_out"), layer = "CountyOutline") %>% 
  st_transform("+proj=longlat")

plot(counties)

# st_crs(counties)$proj4string

# set reference raster

# sb_landsat <- here("files/spatial/data/Landsat7.tif")
# sb_ls_rast <- raster(sb_landsat, band = 2)

gis_tif <- here("files/spatial/county/county_rast1.tif")
gis_county_rast <- raster(gis_tif)
crs(gis_county_rast)
gis_tif
plot(gis_county_rast)
res(gis_county_rast)

# sb_ls_rast <- raster::aggregate(sb_ls_rast, fact = 3, fun = mean)
# 
# plot(sb_ls_rast)
# 
# plot(sbc_rast)
# 
# crs(sb_ls_rast)
# 
# crs(sb_ls_rast) <- ("+proj=lcc +lat_1=34.03333333333333 +lat_2=35.46666666666667 +lat_0=33.5 +lon_0=-118 +x_0=2000000 +y_0=500000.0000000002 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs")
# 
# sbc_rast <- raster(here("files/spatial/data/county.tif"))
# crs(sbc_rast) <- crs(sb_ls_rast)

# make masked raster

# sb_mask <- mask(sb_ls_rast, sbc_rast)
# plot(sb_mask)
# crs(sb_mask) <- ("+proj=aea +lat_1=34.03333333333333 +lat_2=35.46666666666667 +lat_0=33.5 +lon_0=-118 +x_0=2000000 +y_0=500000.0000000002 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs")
# res(sb_mask)
# sb_mask <- disaggregate(sb_mask, fact = 3)
# res(sb_mask)
# crs(sb_mask)

# load in sb county raster 30x30, transform crs (from git allison) - use rasterize, take sb county base raster, rasterize function - field 1 per raster - must be numeric, assign # values to land class types 

all_coord_clean <- all_coord_vals %>% 
  st_as_sf(coords = c("lon", "lat")) %>% 
  st_set_crs(4326) %>% 
  mutate(reclass_fact = as.factor(reclass_cat)) %>% 
  mutate(reclass_num = as.numeric(reclass_fact)) %>% 
  st_transform("+proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +datum=NAD83 +units=us-ft +no_defs")

reclass_levels <- data.frame(levels(all_coord_clean$reclass_fact), c(1:14))

all_coord_spatial <- all_coord_clean %>% 
  as("Spatial")

rast_totalstock <- raster::rasterize(all_coord_spatial, gis_county_rast, field = 'total_stock', fun = mean) 
rast_landclass <- raster::rasterize(all_coord_spatial, gis_county_rast, field = 'reclass_num', fun = "last")

#rast_n2o <- raster::rasterize(all_coord_spatial, gis_county_rast, field = 'noemit', fun = mean)
#rast_abvgc <- raster::rasterize(all_coord_spatial, gis_county_rast, field = 'noemit', fun = mean)

rast_n2o <- raster::rasterize(all_coord_spatial, gis_county_rast, field = 'emit_no_mtco2e_pix', fun = mean)
rast_abvgc <- raster::rasterize(all_coord_spatial, gis_county_rast, field = 'stock_abvgc_mtco2e_pixel', fun = mean)
rast_soilc <- raster::rasterize(all_coord_spatial, gis_county_rast, field = 'stock_soilc_mtco2e_pix', fun = mean)


rast_landclass_fact <- ratify(rast_landclass)
rat <- levels(rast_landclass_fact)[[1]]
rat$names <- unique(levels(all_coord_clean$reclass_fact))
levels(rast_landclass_fact) <- rat

plot(rast_totalstock)
plot(rast_landclass)

# ggplot() +
  # geom_sf(counties, aes(x = ))

colors <- c("gainsboro", "black", "lightsteelblue", "goldenrod", "darkgreen", "darkolivegreen3", "lightslategrey", "darkred", "sandybrown", "cornflowerblue", "chartreuse3", "burlywood3", "purple4", "dodgerblue4") 
  
tmap_mode("view")

tm_shape(rast_landclass_fact) +
  tm_raster(n = 14, pal = colors, alpha = .6) +
  tm_basemap(leaflet::providers$CartoDB.Positron)

tm_shape(rast_totalstock) +
  tm_raster(style = "cont", title = "Total Carbon Stocks (MT Carbon)", palette = "Greens")

# grid <- st_bbox(all_coord_clean)

# add - as("Spatial") - transform from SF to spatial (spatial points)

# Raster plot faster than ggplot 
# aggregate function, 90 or 120 - reduce cell count, run faster # modal argument for aggregate
# try tmap - ggplot if it's not too slow

# all_coord_raster <- rasterize()
# 
# # vals_spatial <- as(all_coord_vals, "Spatial")
# 
# plot(vals_raster)
# 
# st_crs(all_coord_vals)
# 
# all_coords_raster <- raster::rasterize(all_coord_vals)
# 
# ggplot() +
#   geom_sf(data = counties) +
#   geom_sf(data = all_coord_vals,
#               aes(color = reclass_cat),
#               size = .01)

```

