---
title: "Baseline Reference Scenario - SB County NWL GHG emissions and storage"
author: "Carbon Counters"
date: "7/28/2020"
output: 
  html_document: 
    css: bootstrap.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = FALSE)
```

```{r}

# Attach packages
library(tidyverse)
library(tidyr)
library(here)
library(janitor)
library(plotly)
library(kableExtra)
library(effsize)
library(stargazer)
library(broom)

```


```{r}
# Read in data files and clean up, created in carbon inventory script. These files contain # of acres of each ag class according to calag (no landfire)

ag_12 <- read_csv(here::here("files", "results", "ag_final_12.csv")) %>% 
  select(! c(pixels, sqmeter))
ag_16 <- read_csv(here::here("files", "results", "ag_final_16.csv")) %>% 
  clean_names()
ag_16 <- ag_16[, c(1, 6, 2:5, 7)]
ag_19 <- read_csv(here::here("files", "results", "ag_final_19.csv")) %>% 
  select(! c(pixels, sqmeter))

colnames <- c("class", "acres","abvg_c", "soil_c", "no_emit", "net", "year")
colnames(ag_12) = colnames
colnames(ag_16) = colnames
colnames(ag_19) = colnames

# make big dataframe to make calculations easier

all_ag_df <- rbind(ag_12, ag_16) %>% 
  rbind(ag_19) %>% 
  pivot_wider(names_from = class,
              values_from = c(acres, abvg_c, soil_c, no_emit, net)) %>% 
  clean_names()

```

```{r}

# ACREAGE
# Next we will build models to fit a linear regression to each crop category along with total ag acreage

# Total Acres

lm_total_acre <- lm(acres_total ~ year, data = all_ag_df)
lm_total_acre_tidy <- broom::tidy(lm_total_acre)
  
# Annual Row Crops

lm_annual_row <- lm(acres_row_crop ~ year, data = all_ag_df)
lm_annual_row_tidy <- broom::tidy(lm_annual_row)

# Orchard

lm_orchard <- lm(acres_orchard ~ year, data = all_ag_df)
lm_orchard_tidy <- broom::tidy(lm_orchard)

# Vineyard

lm_vineyard<- lm(acres_vineyard ~ year, data = all_ag_df)
lm_vineyard_tidy <- broom::tidy(lm_vineyard)

# Fodder crops

lm_fodder <- lm(acres_fodder ~ year, data = all_ag_df)
lm_fodder_tidy <- broom::tidy(lm_fodder)
```

```{r}
# Now we will use these models to predict acreage (total and per crop type) in 2030

# First, we'll make a data frame of years out to 2030
predict_df_30_acres <- data.frame(year = c(2012, 2016, 2019, 2030))

# Next, we'll predict values for these years using our model
# Total acres
predict_total_run <- predict(lm_total_acre, newdata = predict_df_30_acres)
predict_total_df <- data.frame(predict_df_30_acres, predict_total_run)
predict_total_df <- predict_total_df %>% 
  rename("total_acres_pred" = predict_total_run)

# Annual row crops
predict_annual_run <- predict(lm_annual_row, newdata = predict_df_30_acres)
predict_annual_df <- data.frame(predict_df_30_acres, predict_annual_run)
predict_annual_df
predict_annual_df <- predict_annual_df %>% 
  rename("annual_row_pred" = predict_annual_run)

# Orchard 
predict_orchard_run <- predict(lm_orchard, newdata = predict_df_30_acres)
predict_orchard_df <- data.frame(predict_df_30_acres, predict_orchard_run)
predict_orchard_df
predict_orchard_df <- predict_orchard_df %>% 
  rename("orchard_pred" = predict_orchard_run)

# Vineyard 
predict_vineyard_run <- predict(lm_vineyard, newdata = predict_df_30_acres)
predict_vineyard_df <- data.frame(predict_df_30_acres, predict_vineyard_run)
predict_vineyard_df
predict_vineyard_df <- predict_vineyard_df %>% 
  rename("vineyard_pred" = predict_vineyard_run)

# fodder
predict_fodder_run <- predict(lm_fodder, newdata = predict_df_30_acres)
predict_fodder_df <- data.frame(predict_df_30_acres, predict_fodder_run)
predict_fodder_df
predict_fodder_df <- predict_fodder_df %>% 
  rename("fodder_pred" = predict_fodder_run)

```

```{r}
# Let's make some plots

# These plots compare real data to the regression
ggplot() + 
  geom_point(data = all_ag_df, aes(x = year, y = acres_total)) +
  geom_line(data = predict_total_df, aes(x = year, y = total_acres_pred)) +
  theme_minimal() + 
  labs(x = "year",
       y = "total ag acres")

ggplot() + 
  geom_point(data = all_ag_df, aes(x = year, y = acres_row_crop)) +
  geom_line(data = predict_annual_df, aes(x = year, y = annual_row_pred)) +
  theme_minimal() + 
  labs(x = "year",
       y = "annual row crop acres")

ggplot() + 
  geom_point(data = all_ag_df, aes(x = year, y = acres_orchard)) +
  geom_line(data = predict_orchard_df, aes(x = year, y = orchard_pred)) +
  theme_minimal() + 
  labs(x = "year",
       y = "orchard acres")

ggplot() + 
  geom_point(data = all_ag_df, aes(x = year, y = acres_vineyard)) +
  geom_line(data = predict_vineyard_df, aes(x = year, y = vineyard_pred)) +
  theme_minimal() + 
  labs(x = "year",
       y = "vineyard acres")

ggplot() + 
  geom_point(data = all_ag_df, aes(x = year, y = acres_fodder)) +
  geom_line(data = predict_fodder_df, aes(x = year, y = fodder_pred)) +
    theme_minimal() + 
    labs(x = "year",
       y = "fodder acres")

```

